---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: cosmic-atomic
# description will be included in the image's metadata
description: Universal Blue's base-main image with Cosmic desktop installed along with my tweaks. Made with BlueBuild.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/base-main
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  # - type: files
  #   files:
  #     - source: system
  #       destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: fonts
    fonts:
      nerd-fonts:
        - FiraCode # don't add spaces or "Nerd Font" suffix.
  
  - type: dnf
    repos:
      cleanup: true
      copr:
        enable:
          - ublue-os/packages
    group-install:
      with-optional: true
      packages:
        - cosmic-desktop
    install:
      packages:
        - firewall-config
        - fuse-encfs
        - gnome-disk-utility
        - iwd
        - podman-compose
        - powertop
        - pulseaudio-utils
        - qemu
        - qemu-char-spice
        - qemu-device-display-virtio-gpu
        - qemu-device-display-virtio-vga
        - qemu-device-usb-redirect
        - qemu-img
        - qemu-system-x86-core
        - qemu-user-binfmt
        - qemu-user-static
        - samba
        - setools-console
        - uupd
        - wireguard-tools
    remove:
      auto-remove: true
      packages:
        - firefox
        - firefox-langpacks
  
  - type: brew
    auto-update: true # enable auto-updates
    update-interval: 6h
    auto-upgrade: true # enable auto-upgrades
    upgrade-interval: 6h
    brew-analytics: false # disable telemetry
    nofile-limits: true # increase nofile limits

  - type: default-flatpaks
    notify: true
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: Flathub
      install:
        - best.ellie.StartupConfiguration
        - com.github.PintaProject.Pinta
        - com.github.iwalton3.jellyfin-media-player
        - com.github.tchx84.Flatseal
        - com.github.wwmm.easyeffects
        - com.jwestall.Forecast
        - com.makemkv.MakeMKV
        - com.visualstudio.code
        - dev.heppen.webapps
        - io.github.dvlv.boxbuddyrs
        - io.github.flattool.Warehouse
        - io.missioncenter.MissionCenter
        - io.podman_desktop.PodmanDesktop
        - me.iepure.devtoolbox
        - org.gnome.Calculator
        - org.gnome.Logs
        - org.gnome.Loupe
        - org.gnome.Papers
        - org.gnome.baobab
        - org.gtk.Gtk3theme.adw-gtk3
        - org.gtk.Gtk3theme.adw-gtk3-dark
        - sh.loft.devpod
  
  - type: systemd
    system:
      disabled:
        - flatpak-system-update.timer
      enabled:
        - uupd.timer
  
  - type: script
    snippets:
      - "sed -i 's/AutomaticUpdatePolicy=.*/AutomaticUpdatePolicy=none/g' /etc/rpm-ostreed.conf" # Disable automatic updates per uupd instructions

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

